version: '3'
services:
  mysql_node_1:
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3306:3306
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  mysql_node_2:
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3307:3306
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  mysql_node_3:
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3308:3306
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
